sudo: required
dist: trusty
group: edge

os:
- linux
language: c
compiler:
  - gcc
  - clang

env:
  global:
    - CODECOV_TOKEN=f6610a8e-e06a-4e96-bfec-9dcc57f239e1
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgl1-mesa-dev freeglut3-dev

script:
  - mkdir ./build
  - cd build
  - cmake ..
  - make
  - make check

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
